# Site settings
title: How to Listen to Podcasts
email: jimmy@jimmymarks.com
description: > # this means to ignore newlines until "baseurl:"
  A handy guide for people who have never listened to podcasts and for the nerds who keep beggin them to.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jimmymarks.github.io" # the base hostname & protocol for your site
twitter_username: jimmymarks


# Build settings
markdown: kramdown
